### ISSUE TITLE
Delete the actual List page

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#81]
When all the following issues will be fixed we should delete the actual List page:

- [ ] Use Graylog builtin lookups : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/21
- [ ] Ability to visualize the CSV file content : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/76
- [ ] Ability to import a CSV file : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/77
- [ ] Link to reach data adapter from a wizard rule : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/78
- [ ] Ability to create a list from a wizard rule : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/79
- [ ] Edit the content of a CSV file : https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/80

**Comment by c8y3** [comment]
We need about the import of previous rules with lists...
